name: secondhand_book_selling_platform
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.3.1 <4.0.0"

dependencies:
    cloud_firestore: ^4.16.1
    firebase_auth: ^4.19.1
    firebase_core: ^2.28.0
    firebase_storage: ^11.7.4
    flutter:
        sdk: flutter
    flutter_facebook_auth: ^6.2.0
    go_router: ^13.2.3
    google_sign_in: ^6.2.1
    image_picker: ^1.1.0
    provider: ^6.1.2
    google_fonts: ^6.2.1
    intl: ^0.17.0
    firebase_messaging: ^14.9.4
    firebase_analytics: ^10.10.7
    flutter_local_notifications: ^17.1.2
    http: ^1.2.1
    googleapis: ^13.1.0
    googleapis_auth: ^1.5.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/images/
        - assets/logo.png
        - assets/facebook_logo.png
        - assets/Google.png
        - assets/preview.jpg
        - assets/image.png
        - assets/image5.png
