// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmIPuMaQQ3MtVQv-AoIUpNM55Qnrr_Mi4',
    appId: '1:397661049180:android:741d9bae52e2afe90e3199',
    messagingSenderId: '397661049180',
    projectId: 'secondhand-book-selling-ddda4',
    storageBucket: 'secondhand-book-selling-ddda4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX1W0CeLjT05JSebFNK7KDxPH1xl_FNSA',
    appId: '1:397661049180:ios:b635a7c3078649570e3199',
    messagingSenderId: '397661049180',
    projectId: 'secondhand-book-selling-ddda4',
    storageBucket: 'secondhand-book-selling-ddda4.appspot.com',
    androidClientId: '397661049180-ksbtj4a397tokbmsl24gearh54broht7.apps.googleusercontent.com',
    iosClientId: '397661049180-qveehr5acs62s6vfj3r4re80q6klt6ns.apps.googleusercontent.com',
    iosBundleId: 'com.example.secondhandBookSellingPlatform',
  );

}